service: malaquias-weather-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  about:
    handler: handler.about
    events:
      - http:
          path: about
          method: get

